name: AI Code Reviewer

on:
  push:
    branches: 
      - main
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: AI Code Reviewer
        uses: GwenM-Test/TestGH@main
