name: Test Trivy SCA

on: 
  push:
    branches: [main]

jobs:
  security:
    name: Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@master
        with: 
          scan-type: 'fs'
          severity: 'CRITICAL, HIGH, MEDIUM, LOW'
          format: 'table'
          exit-code: '1'
      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          error: true

  test:
    name: Run Tests
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4